name: DAST Scan with OWASP ZAP

on:
  push:
    branches: [ main ]
  pull_request:
    branches: [ main ]

jobs:
  zap-scan:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout repository
      uses: actions/checkout@v2

    - name: Run OWASP ZAP Baseline Scan
      uses: zaproxy/action-baseline@v0.9.0
      with:
        target: 'https://your-live-app-url.com'  # Replace with the live URL of your app
        cmd_options: '-t 120'  # Optional: set a timeout
        allow_issue_writing: false

    - name: Rename ZAP report
      run: |
        mv zap.out zap_report.html

    - name: Upload ZAP scan report
      uses: actions/upload-artifact@v3
      with:
        name: zap-report
        path: zap_report.html

    - name: Fail if high risk vulnerabilities found
      run: |
        if grep -q "High" zap_report.html; then
          echo "❌ High risk vulnerabilities found!";
          exit 1;
        else
          echo "✅ No high risk vulnerabilities found.";
        fi
