on: [push]

jobs:
  zap_scan:
    runs-on: ubuntu-latest
    name: Scan the webapplication
    steps:
      - name: Checkout
        uses: actions/checkout@v4
        with:
          ref: main
      - name: ZAP Scan
        uses: zaproxy/action-full-scan@v0.12.0
        with:
          token: ${{ secrets.GITHUB_TOKEN }}
          docker_name: 'ghcr.io/zaproxy/zaproxy:stable'
          target: 'https://www.zaproxy.org/'
          #rules_file_name: '.zap/rules.tsv'
          cmd_options: '-t 180'
          fail_action: false

      - name: Fail if High risk vulnerabilities found
        run: |
          if [ -f zap_report.html ]; then
            if grep -iq "<td>High</td>" zap_report.html; then
              echo "❌ High risk vulnerabilities found!"
              exit 1
            else
              echo "✅ No high risk vulnerabilities found."
            fi
          else
            echo "⚠️ ZAP report not found! Skipping check."
            exit 1
          fi

