name: DAST Scan

on:
  push:
    branches:
      - main
  workflow_dispatch:

jobs:
  build-and-scan:
    runs-on: ubuntu-latest

    services:
      web:
        image: node:18
        ports:
          - 3000:3000
        options: >-
          --health-cmd="curl -f http://localhost:3000 || exit 1"
          --health-interval=10s
          --health-timeout=5s
          --health-retries=5
        volumes:
          - ${{ github.workspace }}:/usr/src/app
        env:
          NODE_ENV: production
        entrypoint: sh
        command: >
          -c "cd /usr/src/app &&
              npm install &&
              npm run build &&
              npm run start"

    steps:
      - name: Checkout Code
        uses: actions/checkout@v3

      - name: Wait for web service to be ready
        run: |
          echo "Waiting for web service..."
          sleep 30  # or use curl to poll

      - name: Run ZAP Baseline Scan
        uses: zaproxy/action-baseline@v0.10.0
        with:
          target: http://localhost:3000
          artifact_name: zap_report
          fail_action: false  # Continue even if issues are found

      - name: Run SOOS DAST (Optional)
        uses: soos-io/soos-dast-github-action@v2
        with:
          apiKey: ${{ secrets.SOOS_API_KEY }}
          projectName: "HealthKart"
          scanMode: baseline
          targetURL: http://localhost:3000
          integrationName: GitHub
          branchName: ${{ github.ref_name }}
          buildURI: ${{ github.server_url }}/${{ github.repository }}/actions/runs/${{ github.run_id }}
          logLevel: INFO
          onFailure: continue_on_failure
